### ISSUE TITLE
Both single GPU and multi GPUs give same error: "AttributeError: module 'torch.cuda' has no attribute '_UntypedStorage'"

### ISSUE THREAD

**Issue by IremYoldas** [dbolya/yolact#775]
I'm trying to train Yolact model with my own custom COCO dataset. I wanted to increase batch_size so I tried multiple GPUs and followed your instructions. I took this error and I couldn't find any solution. After that I tried with single GPU because I thought this related with multiple GPUs but I took same error again. 

_P.S.: I used this model before on both Windows and Ubuntu. I couldn't train for this time_

**There is all error**

File "./train.py", line 504, in <module>
    train()
  File "./train.py", line 270, in train
    for datum in data_loader:
  File "path/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "path/python3.7/site-packages/torch/utils/data/dataloader.py", line 1330, in _next_data
    idx, data = self._get_data()
  File "path/python3.7/site-packages/torch/utils/data/dataloader.py", line 1296, in _get_data
    success, data = self._try_get_data()
  File "/pathpython3.7/site-packages/torch/utils/data/dataloader.py", line 1134, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "path/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "path/python3.7/site-packages/torch/multiprocessing/reductions.py", line 303, in rebuild_storage_fd
    shared_cache[fd_id(fd)] = StorageWeakRef(storage)
  File "path/python3.7/site-packages/torch/multiprocessing/reductions.py", line 65, in __setitem__
    self.free_dead_references()
  File "path/python3.7/site-packages/torch/multiprocessing/reductions.py", line 70, in free_dead_references
    if storage_ref.expired():
  File "path/python3.7/site-packages/torch/multiprocessing/reductions.py", line 35, in expired
    return torch.Storage._expired(self.cdata)  # type: ignore[attr-defined]
  File "path/python3.7/site-packages/torch/storage.py", line 753, in _expired
    return eval(cls.__module__)._UntypedStorage._expired(*args, **kwargs)
AttributeError: module 'torch.cuda' has no attribute '_UntypedStorage'

**Comment by IremYoldas** [comment]
I have found a solution. I guess this happens because of num_workers. I've set num_worker to 0 and it still running! I hope this solution helps you too.

**Comment by dragonhaha** [comment]
I met this problem too. It may be caused by the version of Pytorch. I find it works on 1.10.0 but not on 1.12.1

**Comment by HelloSZS** [comment]
Maybe the main problem is pytorch itself, pytorch1.12.0 have the problem. We can try updating it to 1.13.0.
https://github.com/pytorch/pytorch/issues/88839
